apiVersion: v1
kind: Secret
metadata: { name: example-secrets, namespace: ark-operator }
stringData:
  serverPassword: changeMe
  curseforge-api-key: "REPLACE_WITH_YOUR_CURSEFORGE_API_KEY"
---
apiVersion: ark.watteel.com/v1alpha1
kind: ArkCluster
metadata: { name: modded, namespace: ark-operator }
spec:
  clusterID: modded
  maps:
    - id: TheIsland_WP
  globalSettings:
    sessionNameFormat: "Modded - {map}"
    serverPassword: { name: example-secrets, key: serverPassword }
    maxPlayers: 70
    mods: [927090, 1056780]
  storage:
    serverPVCSize: 50Gi
    savesPVCSize: 20Gi
    clusterPVCSize: 5Gi
  service:
    type: LoadBalancer
    gamePortStart: 7777
    rconPortStart: 27020
  modAutoUpdate:
    enabled: true
    intervalMinutes: 60
    curseForgeAPIKeyRef: { name: example-secrets, key: curseforge-api-key }
