---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ark.watteel.com
  resources:
  - arkclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ark.watteel.com
  resources:
  - arkclusters/finalizers
  verbs:
  - update
- apiGroups:
  - ark.watteel.com
  resources:
  - arkclusters/status
  verbs:
  - get
  - patch
  - update
