//go:build !ignore_autogenerated

/*
Copyright 2026 Pascal Watteel.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArkCluster) DeepCopyInto(out *ArkCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArkCluster.
func (in *ArkCluster) DeepCopy() *ArkCluster {
	if in == nil {
		return nil
	}
	out := new(ArkCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArkCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArkClusterList) DeepCopyInto(out *ArkClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArkCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArkClusterList.
func (in *ArkClusterList) DeepCopy() *ArkClusterList {
	if in == nil {
		return nil
	}
	out := new(ArkClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArkClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArkClusterSpec) DeepCopyInto(out *ArkClusterSpec) {
	*out = *in
	if in.Maps != nil {
		in, out := &in.Maps, &out.Maps
		*out = make([]MapSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.GlobalSettings.DeepCopyInto(&out.GlobalSettings)
	out.Storage = in.Storage
	in.Service.DeepCopyInto(&out.Service)
	in.Resources.DeepCopyInto(&out.Resources)
	out.UpdateStrategy = in.UpdateStrategy
	if in.ModAutoUpdate != nil {
		in, out := &in.ModAutoUpdate, &out.ModAutoUpdate
		*out = new(ModAutoUpdateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodSecurityContext != nil {
		in, out := &in.PodSecurityContext, &out.PodSecurityContext
		*out = new(v1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArkClusterSpec.
func (in *ArkClusterSpec) DeepCopy() *ArkClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ArkClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArkClusterStatus) DeepCopyInto(out *ArkClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Maps != nil {
		in, out := &in.Maps, &out.Maps
		*out = make([]MapStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Mods != nil {
		in, out := &in.Mods, &out.Mods
		*out = new(ModStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArkClusterStatus.
func (in *ArkClusterStatus) DeepCopy() *ArkClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ArkClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapRef) DeepCopyInto(out *ConfigMapRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapRef.
func (in *ConfigMapRef) DeepCopy() *ConfigMapRef {
	if in == nil {
		return nil
	}
	out := new(ConfigMapRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalSettings) DeepCopyInto(out *GlobalSettings) {
	*out = *in
	if in.ServerPassword != nil {
		in, out := &in.ServerPassword, &out.ServerPassword
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.AdminPassword != nil {
		in, out := &in.AdminPassword, &out.AdminPassword
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.AllowedPlatforms != nil {
		in, out := &in.AllowedPlatforms, &out.AllowedPlatforms
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Mods != nil {
		in, out := &in.Mods, &out.Mods
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	if in.ExtraOptions != nil {
		in, out := &in.ExtraOptions, &out.ExtraOptions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExtraParams != nil {
		in, out := &in.ExtraParams, &out.ExtraParams
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GameUserSettings != nil {
		in, out := &in.GameUserSettings, &out.GameUserSettings
		*out = new(ConfigMapRef)
		**out = **in
	}
	if in.Game != nil {
		in, out := &in.Game, &out.Game
		*out = new(ConfigMapRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalSettings.
func (in *GlobalSettings) DeepCopy() *GlobalSettings {
	if in == nil {
		return nil
	}
	out := new(GlobalSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MapSpec) DeepCopyInto(out *MapSpec) {
	*out = *in
	if in.Mods != nil {
		in, out := &in.Mods, &out.Mods
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	if in.GameUserSettings != nil {
		in, out := &in.GameUserSettings, &out.GameUserSettings
		*out = new(ConfigMapRef)
		**out = **in
	}
	if in.Game != nil {
		in, out := &in.Game, &out.Game
		*out = new(ConfigMapRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MapSpec.
func (in *MapSpec) DeepCopy() *MapSpec {
	if in == nil {
		return nil
	}
	out := new(MapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MapStatus) DeepCopyInto(out *MapStatus) {
	*out = *in
	if in.LastSaveTime != nil {
		in, out := &in.LastSaveTime, &out.LastSaveTime
		*out = (*in).DeepCopy()
	}
	if in.DrainDeadline != nil {
		in, out := &in.DrainDeadline, &out.DrainDeadline
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MapStatus.
func (in *MapStatus) DeepCopy() *MapStatus {
	if in == nil {
		return nil
	}
	out := new(MapStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModAutoUpdateSpec) DeepCopyInto(out *ModAutoUpdateSpec) {
	*out = *in
	in.CurseForgeAPIKeyRef.DeepCopyInto(&out.CurseForgeAPIKeyRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModAutoUpdateSpec.
func (in *ModAutoUpdateSpec) DeepCopy() *ModAutoUpdateSpec {
	if in == nil {
		return nil
	}
	out := new(ModAutoUpdateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModStatus) DeepCopyInto(out *ModStatus) {
	*out = *in
	if in.LastCheckTime != nil {
		in, out := &in.LastCheckTime, &out.LastCheckTime
		*out = (*in).DeepCopy()
	}
	if in.NextCheckTime != nil {
		in, out := &in.NextCheckTime, &out.NextCheckTime
		*out = (*in).DeepCopy()
	}
	if in.Tracked != nil {
		in, out := &in.Tracked, &out.Tracked
		*out = make([]TrackedMod, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModStatus.
func (in *ModStatus) DeepCopy() *ModStatus {
	if in == nil {
		return nil
	}
	out := new(ModStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpec) DeepCopyInto(out *ServiceSpec) {
	*out = *in
	if in.LoadBalancerIPs != nil {
		in, out := &in.LoadBalancerIPs, &out.LoadBalancerIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpec.
func (in *ServiceSpec) DeepCopy() *ServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrackedMod) DeepCopyInto(out *TrackedMod) {
	*out = *in
	if in.LastChanged != nil {
		in, out := &in.LastChanged, &out.LastChanged
		*out = (*in).DeepCopy()
	}
	if in.AffectedMaps != nil {
		in, out := &in.AffectedMaps, &out.AffectedMaps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrackedMod.
func (in *TrackedMod) DeepCopy() *TrackedMod {
	if in == nil {
		return nil
	}
	out := new(TrackedMod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateStrategy) DeepCopyInto(out *UpdateStrategy) {
	*out = *in
	out.GracefulShutdown = in.GracefulShutdown
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateStrategy.
func (in *UpdateStrategy) DeepCopy() *UpdateStrategy {
	if in == nil {
		return nil
	}
	out := new(UpdateStrategy)
	in.DeepCopyInto(out)
	return out
}
